name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - pytest
  - tk
  - numpy
  - pandas
  - openpyxl
  - pyyaml
  - rdkit
  - loguru
  - biopython
  - pydantic<2
  - mdanalysis
  - gemmi
  - scipy
  - scikit-learn
  - openbabel
  - vina=1.2.7
  - smina=2017.11.9
  - rdock=24.04.204_legacy
  - fpocket
